# Generated by Django 5.1.4 on 2025-01-13 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='items',
        ),
    ]
