# Generated by Django 5.1.4 on 2025-01-13 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_remove_carrito_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='items',
            field=models.ManyToManyField(related_name='en_carritos', through='carrito.CarritoItem', to='carrito.producto'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to='carrito.carrito'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
